kafkaProperties:
  bootstrap.server: 'localhost:9092'
  client.id: 'producer-client-id'
  schema.registry.url: 'http://localhost:8081'
topicProperties:
  name: 'avro-messages-section-5-2'
  topicCheckingProperties:
    numOfAttempts: 5
    timeBetweenAttemptsInMillis: 1000
producerProperties:
  key.serializer: 'org.apache.kafka.common.serialization.IntegerSerializer'
  value.serializer: 'io.confluent.kafka.serializers.KafkaAvroSerializer'